In [1]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# uploading data

from google.colab import files

files.upload()

In [4]:
# reading the csv

df = pd.read_csv("train.csv")
df.head()

ID  Gender Ever_Married  Age Graduated     Profession  Work_Experience  \
0  462809    Male           No   22        No     Healthcare              1.0   
1  462643  Female          Yes   38       Yes       Engineer              NaN   
2  466315  Female          Yes   67       Yes       Engineer              1.0   
3  461735    Male          Yes   67       Yes         Lawyer              0.0   
4  462669  Female          Yes   40       Yes  Entertainment              NaN   

  Spending_Score  Family_Size  Var_1 Segmentation  
0            Low          4.0  Cat_4            D  
1        Average          3.0  Cat_4            A  
2            Low          1.0  Cat_6            B  
3           High          2.0  Cat_6            B  
4           High          6.0  Cat_6            A

In [5]:
df.shape

(8068, 11)

In [6]:
# finding the missing values

df.isnull()


ID  Gender  Ever_Married    Age  Graduated  Profession  \
0     False   False         False  False      False       False   
1     False   False         False  False      False       False   
2     False   False         False  False      False       False   
3     False   False         False  False      False       False   
4     False   False         False  False      False       False   
...     ...     ...           ...    ...        ...         ...   
8063  False   False         False  False      False        True   
8064  False   False         False  False      False       False   
8065  False   False         False  False      False       False   
8066  False   False         False  False      False       False   
8067  False   False         False  False      False       False   

      Work_Experience  Spending_Score  Family_Size  Var_1  Segmentation  
0               False           False        False  False         False  
1                True           False        False  False         False  
2               False           False        False  False         False  
3               False           False        False  False         False  
4                True           False        False  False         False  
...               ...             ...          ...    ...           ...  
8063            False           False        False  False         False  
8064            False           False        False  False         False  
8065            False           False        False  False         False  
8066            False           False        False  False         False  
8067            False           False        False  False         False  

[8068 rows x 11 columns]

In [9]:
# representation of missing data

df.isnull().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [10]:
df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                  int64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
Segmentation        object
dtype: object

In [11]:

df["Work_Experience"].value_counts()

1.0     2354
0.0     2318
9.0      474
8.0      463
2.0      286
3.0      255
4.0      253
6.0      204
7.0      196
5.0      194
10.0      53
11.0      50
12.0      48
13.0      46
14.0      45
Name: Work_Experience, dtype: int64

In [13]:
df["Work_Experience"].isnull().sum()

829

In [14]:
# dropping all the missing value rows

df.dropna(axis=0, inplace=True)

In [15]:
# rechecking for missing data

df.isnull().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

In [16]:
df.shape

(6665, 11)

In [20]:
df["Segmentation"].value_counts()

D    1757
C    1720
A    1616
B    1572
Name: Segmentation, dtype: int64

In [22]:
# setting up the data for model creation

inputs = df.drop(["ID","Segmentation"], axis=1)
target = df["Segmentation"]


In [23]:
inputs

Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0       Male           No   22        No  Healthcare              1.0   
2     Female          Yes   67       Yes    Engineer              1.0   
3       Male          Yes   67       Yes      Lawyer              0.0   
5       Male          Yes   56        No      Artist              0.0   
6       Male           No   32       Yes  Healthcare              1.0   
...      ...          ...  ...       ...         ...              ...   
8062    Male          Yes   41       Yes      Artist              0.0   
8064    Male           No   35        No   Executive              3.0   
8065  Female           No   33       Yes  Healthcare              1.0   
8066  Female           No   27       Yes  Healthcare              1.0   
8067    Male          Yes   37       Yes   Executive              0.0   

     Spending_Score  Family_Size  Var_1  
0               Low          4.0  Cat_4  
2               Low          1.0  Cat_6  
3              High          2.0  Cat_6  
5           Average          2.0  Cat_6  
6               Low          3.0  Cat_6  
...             ...          ...    ...  
8062           High          5.0  Cat_6  
8064            Low          4.0  Cat_4  
8065            Low          1.0  Cat_6  
8066            Low          4.0  Cat_6  
8067        Average          3.0  Cat_4  

[6665 rows x 9 columns]

In [31]:
# using label encoder to convert non-numeric columns into numeric labels. so we can perform further techniques

from sklearn.preprocessing import LabelEncoder

le_Gender = LabelEncoder()
le_Ever_Married = LabelEncoder()
le_Graduated = LabelEncoder()
le_Profession = LabelEncoder()
le_Spending_Score = LabelEncoder()
le_Var_1 = LabelEncoder()

In [25]:
# transforming data

inputs["Gender_n"] = le_Gender.fit_transform(inputs["Gender"])
inputs["Ever_Married_n"] = le_Gender.fit_transform(inputs["Ever_Married"])
inputs["Graduated_n"] = le_Gender.fit_transform(inputs["Graduated"])
inputs["Profession_n"] = le_Gender.fit_transform(inputs["Profession"])
inputs["Spending_Score_n"] = le_Gender.fit_transform(inputs["Spending_Score"])
inputs["Var_1_n"] = le_Gender.fit_transform(inputs["Var_1"])



In [27]:
# transformed data

inputs.head()

Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0    Male           No   22        No  Healthcare              1.0   
2  Female          Yes   67       Yes    Engineer              1.0   
3    Male          Yes   67       Yes      Lawyer              0.0   
5    Male          Yes   56        No      Artist              0.0   
6    Male           No   32       Yes  Healthcare              1.0   

  Spending_Score  Family_Size  Var_1  Gender_n  Ever_Married_n  Graduated_n  \
0            Low          4.0  Cat_4         1               0            0   
2            Low          1.0  Cat_6         0               1            1   
3           High          2.0  Cat_6         1               1            1   
5        Average          2.0  Cat_6         1               1            0   
6            Low          3.0  Cat_6         1               0            1   

   Profession_n  Spending_Score_n  Var_1_n  
0             5                 2        3  
2             2                 2        5  
3             7                 1        5  
5             0                 0        5  
6             5                 2        5

In [28]:
# dropping the original non-numeric columns from the dataframe

inputs.drop(["Gender", "Ever_Married" , "Graduated" ,	"Profession" ,"Spending_Score", "Var_1"], axis=1, inplace=True)

In [29]:
inputs.head()

Age  Work_Experience  Family_Size  Gender_n  Ever_Married_n  Graduated_n  \
0   22              1.0          4.0         1               0            0   
2   67              1.0          1.0         0               1            1   
3   67              0.0          2.0         1               1            1   
5   56              0.0          2.0         1               1            0   
6   32              1.0          3.0         1               0            1   

   Profession_n  Spending_Score_n  Var_1_n  
0             5                 2        3  
2             2                 2        5  
3             7                 1        5  
5             0                 0        5  
6             5                 2        5

In [49]:
target

0       D
2       B
3       B
5       C
6       C
       ..
8062    B
8064    D
8065    D
8066    B
8067    B
Name: Segmentation, Length: 6665, dtype: object

In [34]:
# label encoding the target variable

le_target = LabelEncoder()
target_n = le_target.fit_transform(target)


In [48]:
target_n

array([3, 1, 1, ..., 3, 1, 1])

In [43]:
# divinging dataset into training and testing

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(inputs, target_n, test_size= 0.3, random_state=0)

In [37]:
# model creation

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)


DecisionTreeClassifier()

In [38]:
# model prediction / testing

model.predict(x_test)

array([3, 1, 0, ..., 0, 2, 2])

In [45]:
# model evaluation 

model.score(x_train, y_train)

0.8060021436227224

In [46]:
# making a prediction for a ["female", "married", "36 yrs old", "graduate", "engineer", " 0 exp", "low spending", "family=1", cat_6]

# Age	Work_Experience	Family_Size	Gender_n	Ever_Married_n	Graduated_n	Profession_n	Spending_Score_n	Var_1_n ----- format

model.predict([[36,0,1,0,1,1,2,2,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

This means that the new person belongs to category "A".